site_name: Mitsui Commodity Prediction Challenge
site_description: ML pipeline for commodity prediction competition
site_url: https://kafka2306.github.io/mitsuikaggle/

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Home: 
    - Overview: competition.md
    - Directory Structure: directory_structure.md
  - Architecture:
    - System Architecture: SYSTEM_ARCHITECTURE.md
    - Project Architecture: PROJECT_ARCHITECTURE.md
    - File Structure: FILE_STRUCTURE.md
  - Development:
    - Implementation Roadmap: IMPLEMENTATION_ROADMAP.md
    - Pipeline Management: PIPELINE_MANAGEMENT.md
    - Model Improvement Process: MODEL_IMPROVEMENT_PROCESS.md
  - Experiments:
    - Research Plan: RESEARCH_AND_EXPERIMENTATION_PLAN.md
    - Experiment Status: EXPERIMENT_STATUS_REPORT.md
    - Ensemble Analysis: ENSEMBLE_EXPERIMENT_ANALYSIS.md
  - EDA:
    - Summary: eda_summary.md
    - Results 1: eda_results.md
    - Results 2: eda_results_2.md
    - Results 3: eda_results_3.md
    - Plots: eda_plots.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true